spring.application.name=Universidad

# =====================
# PostgreSQL DataSource
# =====================
spring.datasource.url=jdbc:postgresql://localhost:5432/universidad_db
spring.datasource.username=postgres
spring.datasource.password=salsaypicante
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================
# JPA / Hibernate
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =====================
# Servidor
# =====================
server.port=8080

# =====================
# Swagger / OpenAPI
# =====================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# =====================
# Correo SMTP (Gmail)
# =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santif.arevalo@gmail.com
spring.mail.password=zxna jugm sjdr waoo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
